meta-freescale: update layer
Update meta-freecale layer to more recent revision
in kirkstone branch with updated SRC_URIs to fix fetch
errors due closure of codeaurora.org:

ERROR: libdrm-2.4.109.imx-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.',
'git://source.codeaurora.org/external/imx/libdrm-imx.git;protocol=https;nobranch=1;branch=libdrm-imx-2.4.109')

Change-Id: I00359f96ed92fb0134b1185fe3ee066af6acdec5
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>
(cherry picked from commit 423f21e27de2fe93b87a6941ba8cf441dbce7e5d)
Reviewed-by: Janne Juntunen <janne.juntunen@qt.io>
(cherry picked from commit 7455523a8630901dda939083f62981098a5c5ccb)