mingw: fix gcc compiler with UCRT
GCC needs to use -D__USE_MINGW_ACCESS when built for Windows
and using UCRT. This makes sure that access() works correctly,
otherwise compiler fails with:

 fatal error: cannot execute 'cc1plus': CreateProcess: No such file or directory

and search dirs point to wrong location

 %CC% -print-search-dirs
 install: c:\qt\build\../../lib/aarch64-poky-linux/gcc/aarch64-poky-linux/12.2.0/
 programs: =c:/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/12.2.0/

Fixes: QTBUG-109374
Change-Id: I5c6364b47b24682c669f55251883ba413da9d5ed
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
(cherry picked from commit e8801f88872e216a20cad2706b000fabd32eb102)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>