rust-crosssdk: fix build for aarch64 sdk target
Clear ABIEXTENSION to fix rust-crosssdk build when targeting
aarch64 SDK. By default, it was using 'eabi' which caused error:
Exception: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Similar fix has been done globally on oe-core for x86_64 sdkmachines
in commit adc1c99abaab3d6046edd3a26dd53a31181f97ca.

Change-Id: I140e6a698f9ee631640a3c5d4622e52c0be36020
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>